<?xml version="1.0"?>
<package format="3">

    <!-- basic data -->
    <name>ros_phoenix</name>
    <version>1.0.0</version>
    <description>ROS Support for CTRE Phoenix Library</description>

    <!-- maintainers -->
    <maintainer email="vanderbiltrobotics@gmail.com">Vanderbilt Robotics</maintainer>

    <!-- license information -->
    <license>MIT</license>

    <!-- urls -->
    <url type="website">https://github.com/vanderbiltrobotics/</url>

    <!-- dependencies -->
    <buildtool_depend>ament_cmake</buildtool_depend>
    <buildtool_depend>rosidl_default_generators</buildtool_depend>
    <exec_depend>rosidl_default_runtime</exec_depend>
    <member_of_group>rosidl_interface_packages</member_of_group>
    
    <depend>rclcpp</depend>
    <depend>std_msgs</depend>
    <depend>geometry_msgs</depend>
    <depend>sensor_msgs</depend>

    <export>
       <build_type>ament_cmake</build_type>
    </export>

</package>
